### ISSUE TITLE
Manifest issue : Ch04/Ingress

### ISSUE THREAD

**Issue by ravimanik** [vallard/K8sClass#6]
While applying default-backend.yaml, I'm getting this error - 

error: error validating "default-backend.yaml": error validating data: ValidationError(Ingress.spec): unknown field "backend" in io.k8s.api.networking.v1.IngressSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by vallard** [comment]
hey, sorry I didn't see this!  I've updated it now as `backend` was changed to `defaultBackend`.
